import "./globals.css";
import { ImageProvider } from '@/context/ImageContext'; // Importa o ImageProvider

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        <ImageProvider> {/* Envolvendo a aplicação com o ImageProvider */}
          {children}
        </ImageProvider>
      </body>
    </html>
  );
}
